import { useEffect,useState } from 'react'
import type { Atlas } from './api'
import { rpc } from './cloud'
import { Dialog } from './Dialog'
interface QueueItem { id:string;landmark_id:string;mesh_id:string;label:string;description:string;structure:string;published:boolean;upvotes:number;downvotes:number;reports:number }
export function Admin({atlas,onClose,onOpen}:{atlas:Atlas;onClose():void;onOpen(mesh:string,landmark:string,proposal:string):void}) {
 const [rows,setRows]=useState<QueueItem[]>([]),[sort,setSort]=useState('new'),[offset,setOffset]=useState(0),[unmapped,setUnmapped]=useState<{bucket_label:string;remaining:number}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[target,setTarget]=useState(''),[revision,setRevision]=useState(0)
 useEffect(()=>{let live=true;Promise.all([rpc<QueueItem[]>('pg_admin_queue',{p_sort:sort,p_offset:offset}),rpc<{bucket_label:string;remaining:number}[]>('pg_unmapped')]).then(([q,u])=>{if(live){setRows(q);setUnmapped(u)}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[sort,offset,revision])
 async function act(task:()=>Promise<unknown>){setBusy(true);setError('');try{await task();setRevision(n=>n+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const valid=atlas.parts.some(p=>p.id===target)
 return <Dialog title="Playground administration" onClose={onClose}><p>Inspect the placement on the model before publishing. Votes are community feedback.</p>{error&&<p role="alert" className="error">{error}</p>}<label className="field">Queue<select value={sort} onChange={e=>{setSort(e.target.value);setOffset(0)}}><option value="new">Newest</option><option value="supported">Most supported</option><option value="reported">Reported</option></select></label><div className="admin-queue">{rows.map(p=><article key={p.id}><strong>{p.label}</strong><p className="note">{p.structure} · +{p.upvotes} / −{p.downvotes} · {p.reports} reports{p.published?' · Published':''}</p><div className="row"><button className="outline" onClick={()=>onOpen(p.mesh_id,p.landmark_id,p.id)}>Inspect in 3D</button><button className="outline" disabled={busy||!p.description.trim()} onClick={()=>{if(confirm(p.published?'Unpublish this pin from normal atlas views?':'Publish this exact placement and biology text to the shared dataset?'))void act(()=>rpc('pg_moderate',{p_proposal:p.id,p_action:p.published?'unpublish':'approve'}))}}>{p.published?'Unpublish':'Approve'}</button><button className="ghost" disabled={busy} onClick={()=>{if(confirm('Hide this proposal and withdraw it from publication if necessary?'))void act(()=>rpc('pg_moderate',{p_proposal:p.id,p_action:'hide'}))}}>Hide</button><button className="ghost" disabled={busy||!valid||target===p.mesh_id} onClick={()=>{if(confirm('Move this landmark to the selected target structure? All old placements will be hidden and publication withdrawn. It will need a new placement.'))void act(()=>rpc('pg_move_landmark',{p_landmark:p.landmark_id,p_mesh:target}))}}>Move to target</button></div></article>)}</div><div className="row spread"><button disabled={!offset||busy} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><button disabled={rows.length<50||busy} onClick={()=>setOffset(offset+50)}>Next</button></div><hr/><h3>Structure mapping</h3><label className="field">Target structure<input list="admin-structures" placeholder="Choose the target structure" value={target} onChange={e=>setTarget(e.target.value)}/><datalist id="admin-structures">{atlas.parts.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</datalist></label>{valid&&<p>{atlas.parts.find(p=>p.id===target)?.name}</p>}<p className="note">Mapping adds checklist names only. It never transfers coordinates to another structure.</p><div className="admin-unmapped">{unmapped.map(u=><div className="row spread" key={u.bucket_label}><span>{u.bucket_label} · {u.remaining}</span><button className="outline" disabled={!valid||busy} onClick={()=>{if(confirm(`Map ${u.remaining} checklist names from ${u.bucket_label} to ${atlas.parts.find(p=>p.id===target)?.name}?`))void act(()=>rpc('pg_map_import',{p_bucket:u.bucket_label,p_mesh:target}))}}>Map checklist</button></div>)}</div></Dialog>
}
