import { useCallback,useEffect,useMemo,useRef,useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { ArrowLeft,HelpCircle,MapPin,Plus,Search,SunMoon,ThumbsDown,ThumbsUp,X } from 'lucide-react'
import { loadAtlas,loadMesh,neighbours,type Atlas,type LoadedMesh } from './api'
import { checklist,cloud,comments,placements,restoreDraft,rpc,saveDraft,submit,votes,type Comment,type Draft,type Landmark,type Proposal,type Vote } from './cloud'
import { Viewer,type ViewerHandle } from './Viewer'
import type { PickResult } from './picking'
import { PICK_MESSAGES } from './picking'
import type { ScenePin,ViewName } from './scene'
import { setAppearance,useAppearance } from './theme'
import { Controls,views,type Toggles } from './Controls'
import { Dialog } from './Dialog'
import { Coach } from './Coach'
import { Admin } from './Admin'

export function App() {
 const viewer=useRef<ViewerHandle>(null),{dark}=useAppearance()
 const [atlas,setAtlas]=useState<Atlas|null>(null),[host,setHost]=useState<LoadedMesh|null>(null),[meshId,setMeshId]=useState('')
 const [context,setContext]=useState<LoadedMesh[]>([]),[items,setItems]=useState<Landmark[]>([]),[proposals,setProposals]=useState<Proposal[]>([]),[scores,setScores]=useState<Record<string,Vote>>({})
 const [selected,setSelected]=useState<string|null>(null),[proposalId,setProposalId]=useState<string|null>(null),[draft,setDraft]=useState<Draft|null>(restoreDraft),[placing,setPlacing]=useState(false)
 const [session,setSession]=useState<Session|null>(null),[isAdmin,setIsAdmin]=useState(false),[profile,setProfile]=useState(''),[name,setName]=useState('')
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0)
 const [search,setSearch]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[auth,setAuth]=useState(false),[profileDialog,setProfileDialog]=useState(false),[admin,setAdmin]=useState(false)
 const [tour,setTour]=useState(false),[inspector,setInspector]=useState(true),[listOpen,setListOpen]=useState(true)
 const [discussion,setDiscussion]=useState<Comment[]>([]),[comment,setComment]=useState(''),[moreComments,setMoreComments]=useState(false),[commentRequest,setCommentRequest]=useState(()=>crypto.randomUUID())
 const [toggles,setToggles]=useState<Toggles>({neighbours:false,labels:false,hidden:false,reverse:false}),[width,setWidth]=useState(innerWidth)
 const active=items.find(x=>x.id===selected)??null
 const alternatives=useMemo(()=>proposals.filter(p=>p.landmark_id===selected).sort((a,b)=>(scores[b.id]?.upvotes??0)-(scores[b.id]?.downvotes??0)-((scores[a.id]?.upvotes??0)-(scores[a.id]?.downvotes??0))),[proposals,selected,scores])
 const chosen=alternatives.find(p=>p.id===proposalId)??alternatives.find(p=>p.id===active?.published_proposal)??alternatives[0]??null
 const published=chosen?.id===active?.published_proposal
 const newRequest=(d:Draft):Draft=>({...d,requestId:crypto.randomUUID()})
 const updateDraft=(change:Partial<Draft>)=>setDraft(d=>d?newRequest({...d,...change}):null)
 const tell=(e:unknown)=>setError(e instanceof Error?e.message:String(e))
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await action()}catch(e){tell(e)}finally{setBusy(false)}}
 const discard=()=>!busy&&(!draft||window.confirm('Discard your unsaved proposal?'))
 function chooseStructure(id:string){if(!discard())return;setDraft(null);setSelected(null);setProposalId(null);setMeshId(id);setSearch(false);setPlacing(false);setInspector(false);history.replaceState(null,'',`/playground/?structure=${encodeURIComponent(id)}`)}
 useEffect(()=>{let live=true;loadAtlas().then(a=>{if(!live)return;setAtlas(a);const requested=new URLSearchParams(location.search).get('structure');const restored=restoreDraft();const direct=a.parts.find(p=>p.id===(restored?.meshId??requested));const group=a.concepts.find(c=>c.id===requested)
 if(direct)setMeshId(direct.id);else{setSearch(true);if(group){setQuery(group.name);setNotice('Choose the individual structure you want to annotate.')}}
 }).catch(tell);return()=>{live=false}},[])
 useEffect(()=>{if(!cloud)return;const {data:{subscription}}=cloud.auth.onAuthStateChange((_event,s)=>setSession(s));cloud.auth.getSession().then(({data,error})=>{if(error)tell(error);else setSession(data.session)});return()=>subscription.unsubscribe()},[])
 useEffect(()=>{let live=true;setProfile('');setIsAdmin(false);if(!session||!cloud)return
 Promise.all([cloud.from('pg_profiles').select('display_name').eq('id',session.user.id).maybeSingle(),rpc<boolean>('pg_is_admin')]).then(([p,a])=>{if(!live)return;if(p.error)throw p.error;setProfile(p.data?.display_name??'');setName(p.data?.display_name??'');setIsAdmin(a)}).catch(tell)
 return()=>{live=false}
 },[session?.user.id])
 useEffect(()=>{if(!meshId)return;let live=true;setHost(null);setLoading(true);setError('');setContext([]);setItems([]);setProposals([])
 Promise.all([loadMesh(meshId),checklist(meshId),placements(meshId)]).then(async([h,l,p])=>{if(!live)return;setHost(h);setItems(l);setProposals(p);const updatedScores=await votes(p.map(x=>x.id));if(!live)return;setScores(updatedScores);setLoading(false);try{if(!localStorage.getItem('anatomygo.playground.tour'))setTour(true)}catch{}
 }).catch(e=>{if(live){setLoading(false);tell(e)}});return()=>{live=false}
 },[meshId,refresh,session?.user.id])
 useEffect(()=>{let live=true;if(!atlas||!host||!toggles.neighbours){setContext([]);return}
 Promise.all(neighbours(atlas,host.meta).map(p=>loadMesh(p.id))).then(c=>{if(live)setContext(c)}).catch(e=>{if(live)tell(e)});return()=>{live=false}
 },[atlas,host,toggles.neighbours])
 useEffect(()=>{let live=true;setDiscussion([]);setComment('');setCommentRequest(crypto.randomUUID());if(chosen)comments(chosen.id).then(c=>{if(live){setDiscussion(c);setMoreComments(c.length===30)}}).catch(tell);return()=>{live=false}},[chosen?.id,refresh])
 useEffect(()=>{saveDraft(draft);const guard=(e:BeforeUnloadEvent)=>{if(draft){e.preventDefault();e.returnValue=''}};addEventListener('beforeunload',guard);return()=>removeEventListener('beforeunload',guard)},[draft])
 useEffect(()=>{const resize=()=>setWidth(innerWidth);addEventListener('resize',resize);return()=>removeEventListener('resize',resize)},[])
 const fit=useCallback((v:ViewName)=>viewer.current?.fit(v),[])
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||document.querySelector('dialog[open]'))return;if(e.key.toLowerCase()==='f')fit('oblique');const i=Number(e.key)-1;if(i>=0&&i<views.length)fit(views[i].view);if(e.key==='Escape')setPlacing(false)};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[fit])
 function selectLandmark(id:string){if(!discard())return;setDraft(null);setSelected(id);setProposalId(null);setPlacing(false);setInspector(true);if(width<800)setListOpen(false)}
 function startDraft(fresh=false){if(!host||!discard())return;const source=fresh?null:chosen;setDraft({meshId:host.meta.id,landmarkId:fresh?null:active?.id??null,supersedes:source?.id??null,label:source?.label??(fresh?'':active?.label??''),latin:source?.latin_name??(fresh?'':active?.latin_name??''),description:source?.description??(fresh?'':active?.description??''),anchor:source?{triangle:source.triangle,u:source.u,v:source.v}:null,requestId:crypto.randomUUID(),geometry:host.meta.geometry});setInspector(true);setPlacing(!source);if(fresh){setSelected(null);setProposalId(null)}if(width<800)setListOpen(false)}
 function place(p:PickResult&{ok:true}){if(busy)return;updateDraft({anchor:{triangle:p.triangle,u:p.u,v:p.v}});setPlacing(false);setNotice('Pin placed. Rotate the structure to check it, then save your proposal.')}
 function requireUser(){if(!session){setAuth(true);return false}if(!profile){setProfileDialog(true);return false}return true}
 function save(){if(!requireUser()||!draft)return;const pending=draft;void run(async()=>{const id=await submit(pending);setDraft(null);saveDraft(null);setPlacing(false);setNotice('Proposal saved. It is visible in Playground; publication needs admin approval.');const p=await placements(meshId);setProposals(p);setItems(await checklist(meshId));setScores(await votes(p.map(x=>x.id)));const created=p.find(x=>x.id===id);setSelected(created?.landmark_id??null);setProposalId(id)})}
 async function vote(value:number){if(!chosen||!requireUser())return;await run(async()=>{await rpc('pg_vote',{p_proposal:chosen.id,p_value:scores[chosen.id]?.mine===value?0:value});setScores(await votes(proposals.map(p=>p.id)))})}
 const pins=useMemo(()=>{const result:ScenePin[]=[];for(const l of items){const p=(l.id===selected?chosen:null)??proposals.find(p=>p.id===l.published_proposal)??proposals.find(p=>p.landmark_id===l.id);if(p&&(!draft||draft.landmarkId!==l.id))result.push({id:p.id,label:p.label,triangle:p.triangle,u:p.u,v:p.v,reviewed:p.id===l.published_proposal})}
 const visible=result.slice(0,100);if(chosen&&!visible.some(p=>p.id===chosen.id)&&!draft)visible.push({id:chosen.id,label:chosen.label,triangle:chosen.triangle,u:chosen.u,v:chosen.v});if(draft?.anchor)visible.push({id:'draft',label:draft.label||'Your pin',...draft.anchor});return visible
 },[items,proposals,chosen,draft,selected])
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();const group=atlas.concepts.find(c=>c.name.toLowerCase()===term);return atlas.parts.filter(p=>p.name.toLowerCase().includes(term)||p.id.toLowerCase().includes(term)||group?.elements.includes(p.id)).slice(0,100)},[atlas,query])
 const hasInspector=inspector&&!!(active||draft)
 const insets=width<800?{left:0,right:56,top:110,bottom:hasInspector?Math.min(innerHeight*.44,400):90}:{left:listOpen?(width<1100?260:300):25,right:hasInspector?(width<1100?375:430):80,top:100,bottom:85}
 const returnLink=meshId?`/?structure=${encodeURIComponent(meshId)}&isolate=1`:'/'
 return <main className={`studio public-studio ${hasInspector?'has-inspector':''}`}>
  <div className="stage" data-coach="stage">{host&&<Viewer key={host.meta.id} ref={viewer} host={host} context={context} pins={pins} selected={draft?.anchor?'draft':chosen?.id??null} mode={placing?'place':'orbit'} allowReverse={toggles.reverse} showHidden={toggles.hidden} showOtherLabels={toggles.labels} dark={dark} insets={insets} onPlace={place} onPickRefused={p=>setNotice(PICK_MESSAGES[p.reason])} onPinClick={id=>{const p=proposals.find(p=>p.id===id);if(p){selectLandmark(p.landmark_id);setProposalId(p.id)}}}/>}</div>
  <header className="public-header"><div><a href={returnLink} onClick={e=>{if(!discard())e.preventDefault()}} className="back-link"><ArrowLeft size={14}/> AnatomyGo</a><h1>Playground</h1><span className="identity-meta">{host?.meta.name??'Explore. Place. Contribute.'}</span></div><div className="header-actions"><button className="outline" onClick={()=>setSearch(true)}><Search size={15}/><span>Structure</span></button><button className="icon" aria-label="Change appearance" onClick={()=>setAppearance(dark?'light':'dark')}><SunMoon size={18}/></button><button className="icon" aria-label="Show tutorial" onClick={()=>setTour(true)}><HelpCircle size={18}/></button>{isAdmin&&<button className="outline" onClick={()=>setAdmin(true)}>Admin</button>}<button className="outline" disabled={busy} onClick={()=>session?void run(async()=>{await cloud!.auth.signOut();setNotice('Signed out.') }):setAuth(true)}>{session?'Sign out':'Sign in'}</button></div></header>
  <button className="checklist-toggle outline glass" onClick={()=>setListOpen(!listOpen)}>{listOpen?'Hide checklist':'Show checklist'}</button>
  {listOpen&&<aside className="checklist-panel glass" data-coach="checklist"><div className="row spread"><h2>Landmarks</h2><span className="count">{items.length}</span></div><input aria-label="Filter landmarks" placeholder="Find a landmark…" value={filter} onChange={e=>setFilter(e.target.value)}/><button className="primary" data-coach="add" disabled={!host||busy} onClick={()=>startDraft(true)}><Plus size={15}/>Add landmark</button><div className="public-checklist">{items.filter(l=>l.label.toLowerCase().includes(filter.toLowerCase())).map(l=>{const count=proposals.filter(p=>p.landmark_id===l.id).length;return <button key={l.id} className={selected===l.id?'selected':''} onClick={()=>selectLandmark(l.id)}><span>{l.label}</span><small>{l.published_proposal?'Published':count?`${count} proposal${count===1?'':'s'}`:'Needs a pin'}</small></button>})}{!items.length&&!loading&&<p className="muted">No landmarks added yet. Add the first for this structure.</p>}</div></aside>}
  {host&&<Controls onFit={fit} toggles={toggles} onToggle={k=>setToggles(t=>({...t,[k]:!t[k]}))}/>}
  {inspector&&(draft||active)&&<aside className="landmark-card glass public-inspector" data-coach="inspector"><header className="row spread"><span className="eyebrow">{draft?'Your proposal':published?'Published':'Community suggestions'}</span><button className="icon" aria-label="Collapse pin details" onClick={()=>setInspector(false)}><X size={17}/></button></header><div className="inspector-scroll">
   {draft?<><label className="field">Landmark name<input disabled={busy} maxLength={160} value={draft.label} onChange={e=>updateDraft({label:e.target.value})}/></label><label className="field">Latin name (optional)<input disabled={busy} maxLength={200} value={draft.latin} onChange={e=>updateDraft({latin:e.target.value})}/></label><label className="field">Biology description<textarea disabled={busy} rows={4} maxLength={4000} value={draft.description} onChange={e=>updateDraft({description:e.target.value})}/></label>{!draft.landmarkId&&items.some(l=>l.label.toLowerCase()===draft.label.trim().toLowerCase())&&<p className="warning">A landmark with this name is already in the checklist. Check it before adding another.</p>}<p className="muted">{draft.anchor?'Pin placed. Inspect it from another view.':'Choose a point on the structure.'}</p><button className="outline" disabled={busy} onClick={()=>setPlacing(!placing)}><MapPin size={15}/>{placing?'Cancel placement':draft.anchor?'Move pin':'Place pin'}</button><p className="note">Your work is unsaved until the server confirms it.</p></>:<><h2>{chosen?.label??active?.label}</h2>{(chosen?.latin_name??active?.latin_name)&&<p className="latin">{chosen?.latin_name??active?.latin_name}</p>}<p className="biology">{chosen?.description??active?.description}</p>{alternatives.length>0&&<label className="field">Compare placements<select aria-label="Compare placements" value={chosen?.id??''} disabled={busy} onChange={e=>setProposalId(e.target.value)}>{alternatives.map((p,i)=><option key={p.id} value={p.id}>{p.id===active?.published_proposal?'Published · ':''}{p.pg_profiles?.display_name??'Imported suggestion'} · {i+1}</option>)}</select></label>}
   {chosen&&<><div className="votes"><button className="outline" aria-label="Upvote placement" aria-pressed={scores[chosen.id]?.mine===1} disabled={busy||chosen.author_id===session?.user.id} onClick={()=>void vote(1)}><ThumbsUp size={16}/>{scores[chosen.id]?.upvotes??0}</button><button className="outline" aria-label="Downvote placement" aria-pressed={scores[chosen.id]?.mine===-1} disabled={busy||chosen.author_id===session?.user.id} onClick={()=>void vote(-1)}><ThumbsDown size={16}/>{scores[chosen.id]?.downvotes??0}</button></div><p className="note">Votes refer to this placement. They help the admin assess suggestions.</p></>}
   <button className="primary wide" disabled={busy||!host} onClick={()=>startDraft()}><MapPin size={16}/>{chosen?'Suggest a correction':'Place this landmark'}</button>
   {chosen&&<><div className="row pin-actions">{chosen.author_id===session?.user.id&&!published&&<button className="ghost" disabled={busy} onClick={()=>{if(window.confirm('Delete your unpublished proposal? It will disappear from public view.'))void run(async()=>{await rpc('pg_withdraw',{p_proposal:chosen.id});setRefresh(x=>x+1);setProposalId(null)})}}>Delete my proposal</button>}<button className="ghost" onClick={()=>{if(!requireUser())return;const reason=window.prompt('What needs attention? Include the correct structure if this pin is in the wrong place.');if(reason)void run(async()=>{await rpc('pg_report',{p_proposal:chosen.id,p_reason:reason});setNotice('Report sent to the admin.')})}}>Report a problem</button></div>
   <section className="comments"><h3>Discussion</h3>{discussion.map(c=><article key={c.id}><div className="row spread"><strong>{c.pg_profiles?.display_name??'Contributor'}</strong>{(c.author_id===session?.user.id||isAdmin)&&<button className="ghost" aria-label="Delete comment" onClick={()=>void run(async()=>{await rpc('pg_remove_comment',{p_comment:c.id});setDiscussion(await comments(chosen.id))})}>Delete</button>}</div><p>{c.body}</p></article>)}{!discussion.length&&<p className="muted">Explain what looks right or what could be improved.</p>}{moreComments&&<button className="ghost" onClick={()=>void run(async()=>{const more=await comments(chosen.id,discussion.at(-1)?.created_at);setDiscussion(d=>[...d,...more]);setMoreComments(more.length===30)})}>Older comments</button>}<label className="field">Your comment<textarea disabled={busy} rows={2} maxLength={2000} value={comment} onChange={e=>{setComment(e.target.value);setCommentRequest(crypto.randomUUID())}}/></label><button className="outline" disabled={busy||!comment.trim()} onClick={()=>{if(!requireUser())return;void run(async()=>{await rpc('pg_comment',{p_proposal:chosen.id,p_body:comment,p_request:commentRequest});setComment('');setCommentRequest(crypto.randomUUID());setDiscussion(await comments(chosen.id))})}}>Post comment</button></section></>}
   </>}
  </div>{draft&&<footer className="row"><button className="primary" disabled={busy||!draft.anchor||!draft.label.trim()||!host||draft.geometry!==host.meta.geometry} onClick={save}>{busy?'Saving…':'Save proposal'}</button><button className="ghost" disabled={busy} onClick={()=>{if(discard()){setDraft(null);setPlacing(false)}}}>Discard</button></footer>}</aside>}
  {!inspector&&(active||draft)&&<button className="reopen-inspector outline glass" onClick={()=>setInspector(true)}>Show pin details</button>}
  <div className="public-status" aria-live="polite">{loading?'Loading structure…':placing?'Click the structure to place your pin. Drag to rotate.':notice||(!cloud?'Local preview · contributions are not connected yet.':'Community proposals appear here. Approved pins appear in the atlas.')}{pins.length>=100&&<span> · Showing up to 100 landmarks; select a checklist item to inspect it.</span>}</div>
  {error&&<div className="public-error glass" role="alert"><span>{error}</span><button className="ghost" onClick={()=>{setError('');setRefresh(x=>x+1)}}>Retry</button><button className="icon" aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}
  {search&&<Dialog title="Choose a structure" onClose={()=>setSearch(false)}><input autoFocus aria-label="Search structures" placeholder="Name or structure ID…" value={query} onChange={e=>setQuery(e.target.value)}/><p className="note">Every model structure is available, even when its checklist is empty.</p><div className="structure-results">{results.map(p=><button key={p.id} onClick={()=>chooseStructure(p.id)}><span>{p.name}</span><small>{p.system}</small></button>)}</div></Dialog>}
  {auth&&<Dialog title="Sign in to contribute" onClose={()=>setAuth(false)}><p>Save pins, vote and join the discussion. Your current placement stays in this tab.</p>{!cloud?<p className="warning">Online contributions are not connected in this preview.</p>:<><button className="primary wide" disabled={busy} onClick={()=>void run(async()=>{saveDraft(draft);const {error}=await cloud!.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+`/playground/?structure=${encodeURIComponent(meshId)}`}});if(error)throw error})}>Continue with Google</button></>}</Dialog>}
  {profileDialog&&<Dialog title="Your public name" onClose={()=>setProfileDialog(false)}><p>This name appears beside your proposals and comments. Your email stays private.</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{await rpc('pg_set_profile',{p_name:name});setProfile(name.trim());setProfileDialog(false);setNotice('Profile saved. You can now save your proposal or continue contributing.')})}}><label className="field">Display name<input minLength={2} maxLength={60} required value={name} onChange={e=>setName(e.target.value)}/></label><button className="primary" disabled={busy}>Save name</button></form></Dialog>}
  {tour&&!search&&!auth&&host&&<Coach onClose={()=>setTour(false)}/>}
  {admin&&isAdmin&&atlas&&<Admin atlas={atlas} onClose={()=>{setAdmin(false);setRefresh(x=>x+1)}} onOpen={(mesh,id,proposal)=>{if(!discard())return;setAdmin(false);setDraft(null);setMeshId(mesh);setSelected(id);setProposalId(proposal);setInspector(true);setRefresh(x=>x+1)}}/>}
 </main>
}
